version: "3.4"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "3875:3000"
    volumes:
      - "./server/var:/home/server/var"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - "3876:3000"
    restart: unless-stopped
